// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaztetwnictrpbetfcxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthenRldHduaWN0cnBiZXRmY3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTMzNzYsImV4cCI6MjA2MjIyOTM3Nn0.WHJR8xbBY07mbUYjaPQq3cJv7_HYKQrWD0lic9qBUlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);